### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by hungryquiter** [ganeshjawahar/mem_absa#1]
i want to know the data in this project is the data of  Semeval 2014 or the data of  Semeval 2016.

**Comment by ganeshjawahar** [comment]
Semeval 2014 <= the version used in the original paper.

**Comment by hungryquiter** [comment]
whether is the Restaurants_Test_Gold.xml standard answer，　where do you download it. thank you

**Comment by ganeshjawahar** [comment]
search for 'gold' in google groups: http://alt.qcri.org/semeval2014/task4/index.php?id=google-group
