### ISSUE TITLE
Training Fails on Laptop Dataset

### ISSUE THREAD

**Issue by 0220joey** [ganeshjawahar/mem_absa#5]
When I try to train using the recommended Glove 300D vectors and on the Laptop Dataset as stated in the README the following error occurs:
"Traceback (most recent call last):
  File "main.py", line 61, in <module>
    tf.app.run()
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 57, in main
    model.build_model()
  File "/Users/joey/Desktop/marketanalytics/mem_absa/model.py", line 107, in build_model
    self.build_memory()
  File "/Users/joey/Desktop/marketanalytics/mem_absa/model.py", line 79, in build_memory
    a_til_concat = tf.concat(2, [til_hid3dim, Ain])
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/joey/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead."

**Comment by 0220joey** [comment]
Answering my own question, this is a backwards compatibility issue. Tensorflow API has been updated and the tf.concat function args have been shuffled a bit. tf.batch_matmul is depricated as well and should be replaced with tf.matmul, among others.

**Comment by weijia1994** [comment]
**I changed the order of arguments of tf.concat, but the error still exists. May I know how to solve this problem? Thank you!**
TypeError                                 Traceback (most recent call last)
<ipython-input-59-ff4524316b84> in <module>()
      2 with tf.Session() as sess:
      3     model = MemN2N(FLAGS, sess)
----> 4     model.build_model()
      5     model.run(train_data, test_data)

/home/weijia/Text-Mining/AspectLevel/model.py in build_model(self)
    105 
    106     def build_model(self):
--> 107         self.build_memory()
    108 
    109         self.W = tf.Variable(tf.random_normal([self.edim, 3], stddev=self.init_std))

/home/weijia/Text-Mining/AspectLevel/model.py in build_memory(self)
     77             til_hid = tf.tile(self.hid[-1], [1, self.mem_size])
     78             til_hid3dim = tf.reshape(til_hid, tf.stack([-1, self.mem_size, self.edim]))
---> 79             a_til_concat = tf.concat([til_hid3dim, Ain],2)
     80             til_bl_wt = tf.tile(self.BL_W, [self.batch_size, 1])
     81             til_bl_3dim = tf.reshape(til_bl_wt, [self.batch_size, -1, 2 * self.edim])

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.pyc in concat(values, axis, name)
   1041       ops.convert_to_tensor(axis,
   1042                             name="concat_dim",
-> 1043                             dtype=dtypes.int32).get_shape(
   1044                             ).assert_is_compatible_with(tensor_shape.scalar())
   1045       return identity(values[0], name=scope)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, preferred_dtype)
    674       name=name,
    675       preferred_dtype=preferred_dtype,
--> 676       as_ref=False)
    677 
    678 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    739 
    740         if ret is None:
--> 741           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    742 
    743         if ret is NotImplemented:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.pyc in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    111                                          as_ref=False):
    112   _ = as_ref
--> 113   return constant(v, dtype=dtype, name=name)
    114 
    115 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
    100   tensor_value = attr_value_pb2.AttrValue()
    101   tensor_value.tensor.CopyFrom(
--> 102       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    103   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    104   const_tensor = g.create_op(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    372       nparray = np.empty(shape, dtype=np_dt)
    373     else:
--> 374       _AssertCompatible(values, dtype)
    375       nparray = np.array(values, dtype=np_dt)
    376       # check to them.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.pyc in _AssertCompatible(values, dtype)
    300     else:
    301       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 302                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    303 
    304 

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by loveJasmine** [comment]
which tensorflow version you used?
after change the tf.batch_matmul  to tf.matmul , I got the same error yet
